name: Cloud storage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: |
        cd ..
        npm install

    - name: Install backend dependencies
      run: |
        cd sample
        npm install

    - name: Build backend nodejs
      run: |
        cd sample
        npm run build
